update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to Play Store internal track"
  lane :internal do
    sh "cd .. && flutter build appbundle"
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      json_key: ENV["FASTLANE_JSON_KEY_FILE"]
    )
  end
end
