name: Deploy to Play Store
on:
  # automated run
  push:
    branches: [main, "releases/**"]

  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "internal"
        type: choice
        options:
          - beta
          - promote_to_production
          - internal

# Declare default permissions as read-only.
permissions: read-all

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Setup up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v

      # Checkout the repository
      - name: Checkout repository code
        uses: actions/checkout@v2

      # Setup Ruby, Bundler, and Gemfile dependencies.
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      # Configure Keystore.
      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
          echo "$PLAY_STORE_CONFIG_JSON" >> fastlane/play_store_config.json
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: ./android

      # Build and deploy with Fastlane.
      - name: Run Fastlane
        run: |
          bundle install
          bundle exec fastlane ${{ github.event.inputs.lane || 'internal' }}
        env:
          FASTLANE_JSON_KEY_FILE: fastlane/play_store_config.json
        working-directory: ./android
