#
# A simple way to automate your Flutter app deployment using GitHub Actions. 
# Note: this workflow does not work as-is, you will need to add the relevant secrets and keys
# as well as update the fastlane match configuration to match your app's bundle identifier.
#

name: Flutter CI/CD 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd android && fastlane internal
        env:
          JSON_KE_DATA: ${{ secrets.JSON_KEY }}